version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:15
    command:
      - "postgres"
      - "-c"
      - "max_connections=5"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "effective_cache_size=128MB"
      - "-c"
      - "work_mem=32MB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=1GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "lev39"
      POSTGRES_USER: "nikita"
      POSTGRES_PASSWORD: "nikita"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ../lokamativ-bot:/docker-entrypoint-initdb.d/init.sql
      - lokamativ-bot-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nikita -d nikita"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
    networks:
      - postgres
  bot:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - postgres

volumes:
  lokamativ-bot-data:

networks:
  postgres:
    driver: bridge